### ISSUE TITLE
Existing module "Interactive Tree" is disturbed

### ISSUE THREAD

**Issue by hartenthaler** [huhwt/huhwt-xtv#1]
When this module is activated then the existing module "Interactive Tree" (in the tab on individual page as well in diagrams) is disturbed by showing a scroll bar that was there never before.

**Comment by huhwt** [comment]
The reason was extending the css-class 'tv_in' by scrolling-capabilities. This class is also present in default webtrees interactive-treeview. Fixed by creating own css-class. Please use v1.0.5 ...
