### ISSUE TITLE
Not sure if this is an issue!

### ISSUE THREAD

**Issue by RAMINCNZ** [huhwt/huhwt-xtv#19]
Top right corner when on the Interactive XT tab shows as per attached
![InteractiveTreeXT-1](https://github.com/user-attachments/assets/f780b83e-b9ef-496d-83f9-6d12bd54b809)

WebTrees v2.2.1 PHP v8.3.x

IF not a 'issue' then I would prefer the option NOT to show!!

Many Thanks

Rick M
New Zealand - Nu Tirani

**Comment by huhwt** [comment]
Well, it's not an issue ... it's the PageMap, which you can use to navigate in the XTV view - but the benefit will probably only be apparent when the view is maximised or in fullscreen mode and the number of people has become so large that they can no longer all be displayed in the visible section.
I will add a switch to control this option.
I agree: in the individuals tab with only a few people in the view, it's more a kind of bug than a feature ...

**Comment by huhwt** [comment]
PageMap is only shown when the view is expanded. Additionally, the PageMap can be shown or hidden using an option.
