### ISSUE TITLE
Diagramme aufrufen alternative Möglichkeit

### ISSUE THREAD

**Issue by arbor95** [huhwt/huhwt-xtv#5]
Ich nutze auch eine sogenannte alternative Möglichkeit Diagramme aufzurufen.

Da gibt es bisher 4 Möglichkeiten zur Auswahl, wovon eine das "Interaktive Sanduhr Diagramm" ist.

Da wird allerdings der Standard, mit Ganzseiten Erweterung, aufgerufen. 

Könntest du das so machen, das da, falls installiert, deine Erweiterung verwendet wird?
![Screenshot_20210710-180145_Chrome](https://user-images.githubusercontent.com/6124739/125169450-7d6e4280-e1aa-11eb-830f-5db984c95cb3.jpg)
![Screenshot_20210710-180954_Chrome](https://user-images.githubusercontent.com/6124739/125169453-7e06d900-e1aa-11eb-9dc7-07634e145f5f.jpg)

**Comment by huhwt** [comment]
Ich verstehe aktuell nicht, wo das in Erscheinung tritt ... Ich habe die Option 'Alternative Diagramme' mal deaktiviert, danach aber keine Veränderung bemerkt. Wo werden denn die anderen/sonstigen Diagramme angeboten? Und welche wären das?

**Comment by arbor95** [comment]
I created a little thread for that:
https://www.webtrees.net/index.php/en/forum/help-for-release-2-1-x/38221-charts-alternative

**Comment by huhwt** [comment]
No chance, options in this module are hard coded.
